---
version: "3.7"


x-node-env:
  &global_env
  DEPLOYED_ENVIRONMENT: dev
  NODE_ID: "{{.Node.ID}}"
  NODE_HOSTNAME: "{{.Node.Hostname}}"
  SERVICE_ID: "{{.Service.ID}}"
  SERVICE_NAME: "{{.Service.Name}}"
  SERVICE_LABELS: "{{js .Service.Labels}}"
  SERVICE_DNSPEERS: "tasks.{{.Service.Name}}"
  STACK_IMAGE: '{{index .Service.Labels "com.docker.stack.image"}}'
  STACK_NAMESPACE: '{{index .Service.Labels "com.docker.stack.namespace"}}'
  TASK_ID: "{{.Task.ID}}"
  TASK_NAME: "{{.Task.Name}}"
  TASK_SLOT: "{{.Task.Slot}}"

services:

#NOTE: meant to be a box to 'docker exec -it <container> bash' into and have full centos operating system available
#      on the backend network.
  devboxspy:
    image: davequick/image:spy
    hostname: '{{index .Service.Labels "com.docker.stack.namespace"}}-spy-{{.Task.Slot}}'
    labels:
      gg.dq.description: "spy"
    environment:
      <<: *global_env
    command: ["sleep", "infinity"]
    networks:
      - backend

#NOTE: Vanilla nginx
#  website:
#    image: nginx
#    environment:
#      <<: *global_env
#    labels:
#      - "traefik.frontend.rule=Host:test.davequick.com.localhost"
#    networks:
#      - backend
#Sample: Welcome to nginx!

#NOTE: simple text
#  whoami:
#    image: containous/whoami # A container that exposes an API to show its IP address
#    environment:
#      <<: *global_env
#    labels:
#      - "traefik.frontend.rule=Host:whoami.docker.localhost"
#    deploy:
#      replicas: 2
#    networks:
#      - backend
#
#Sample:
#  Hostname: 072df99014a9
#  IP: 127.0.0.1
#  IP: 10.0.8.214
#  IP: 172.18.0.6
#  GET / HTTP/1.1
#  Host: whoami.docker.localhost
#  User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
#  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8
#  Accept-Encoding: gzip, deflate, br
#  Accept-Language: en-US,en;q=0.9
#  Cookie: gsScrollPos-4983=0; gsScrollPos-710=0; gsScrollPos-2586=0
#  Upgrade-Insecure-Requests: 1
#  X-Forwarded-For: 10.255.0.2
#  X-Forwarded-Host: whoami.docker.localhost
#  X-Forwarded-Port: 80
#  X-Forwarded-Proto: http
#  X-Forwarded-Server: 35d17bec6405
#  X-Real-Ip: 10.255.0.2

#NOTE: handy UI demo that shows which container it is talking to - repeated query
#  demo:
#    image: ehazlett/docker-demo
#    labels:
#      - "traefik.frontend.rule=Host:test.davequick.localhost"
#    deploy:
#      replicas: 20
#    networks:
#      - backend
