---
version: "3.7"

services:
  healthcheck:
    image: davequick/image:healthcheck
    labels:
      gg.dq.desscription: "healthcheck"
    environment:
      NODE_ID: "{{.Node.ID}}"
      NODE_HOSTNAME: "{{.Node.Hostname}}"
      SERVICE_ID: "{{.Service.ID}}"
      SERVICE_NAME: "{{.Service.Name}}"
      SERVICE_LABELS: "{{js .Service.Labels}}"
      SERVICE_DNSPEERS: "tasks.{{.Service.Name}}"
      TASK_ID: "{{.Task.ID}}"
      TASK_NAME: "{{.Task.Name}}"
      TASK_SLOT: "{{.Task.Slot}}"
    ports:
      - 6969:3001
    deploy:
      mode: global
      restart_policy:
        condition: any
        delay: 0
        endpoint_mode: dnsrr
