#ssh node01.dq.gg -t /sbin/reboot now
#ssh node02.dq.gg -t /sbin/reboot now
#ssh node03.dq.gg -t /sbin/reboot now
#ssh node04.dq.gg -t /sbin/reboot now
ssh node05.dq.gg -t /sbin/reboot now
ssh node06.dq.gg -t /sbin/reboot now
ssh node07.dq.gg -t /sbin/reboot now
ssh node08.dq.gg -t /sbin/reboot now
ssh node09.dq.gg -t /sbin/reboot now
ssh node10.dq.gg -t /sbin/reboot now
ssh node11.dq.gg -t /sbin/reboot now
ssh node12.dq.gg -t /sbin/reboot now
ssh node13.dq.gg -t /sbin/reboot now
ssh node14.dq.gg -t /sbin/reboot now
ssh node15.dq.gg -t /sbin/reboot now
ssh node16.dq.gg -t /sbin/reboot now
ssh node17.dq.gg -t /sbin/reboot now
