---
version: "3.7"

services:
  consul:
    image: consul
    hostname: "consul-{{.Task.Slot}}"
    labels:
      gg.dq.desscription: "consul"
    environment:
      NODE_ID: "{{.Node.ID}}"
      NODE_HOSTNAME: "{{.Node.Hostname}}"
      SERVICE_ID: "{{.Service.ID}}"
      SERVICE_NAME: "{{.Service.Name}}"
      SERVICE_LABELS: "{{js .Service.Labels}}"
      SERVICE_DNSPEERS: "tasks.{{.Service.Name}}"
      TASK_ID: "{{.Task.ID}}"
      TASK_NAME: "{{.Task.Name}}"
      TASK_SLOT: "{{.Task.Slot}}"
      CONSUL_LOCAL_CONFIG: '{ "datacenter":"docker-cluster", "enable_debug":true, "leave_on_terminate": true, "skip_leave_on_interrupt": false }'
    command: ["agent","-retry-join=tasks.consul", "-server=true", "-bootstrap-expect=3"]
    dns:
      - 8.8.8.8
    networks:
      - backend
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 30s
networks:
  backend:
    external: true
    driver: overlay
    internal: true
    attachable: true
