---
version: '3.7'

services:

  elasticsearch:
    image: davequick/image:elasticsearch
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1

configs:
  elastic_config:
    file: ./elasticsearch.yml

networks:
  backend:
    existing: true