ARG ELK_VERSION
FROM docker.elastic.co/elasticsearch/elasticsearch-oss:${ELK_VERSION}
LABEL maintainer="dq@dq.gg"
# Add elasticsearch plugins setup here
# i.e.: RUN elasticsearch-plugin install analysis-icu
