---
version: '3.7'

services:

  elasticsearch:
    image: davequick/image:elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1

configs:
  elastic_config:
    file: ./config/elasticsearch.yml

networks:
  backend:
    existing: true